<?php

declare(strict_types=1);

/**
 * Jeu de communautes initiales avec donnees enrichies pour les pages detail.
 * Images locales uniquement (public/diapo/).
 */

$diapo = [
    '/diapo/_MG_0735.jpg',
    '/diapo/CCS_5506.jpg',
    '/diapo/CCS_5535.jpg',
    '/diapo/IMG_0121.jpg',
    '/diapo/IMG_0186.jpg',
    '/diapo/IMG_9473.jpg',
    '/diapo/IMG_9477.jpg',
    '/diapo/IMG_9584.jpg',
    '/diapo/IMG_9584 (1).jpg',
    '/diapo/IMG_9590.jpg',
    '/diapo/PXL_20260516_090047229.jpg',
];

$pick = static fn (int $i): string => $diapo[$i % count($diapo)];

return [
    [
        'name' => 'GDG Lomé',
        'shortDescription' => 'La communauté Google Developers de Lomé — conférences, ateliers et DevFest.',
        'description' => "Le Google Developer Group de Lomé est une communauté de passionnés des technologies Google (Android, Web, Firebase, Google Cloud, AI). Nous organisons des conférences, ateliers de code et le célèbre DevFest Lomé annuel pour connecter et former les talents locaux.",
        'mission' => "Démocratiser l'accès aux technologies Google au Togo et créer un écosystème où chaque développeur peut apprendre, partager et grandir professionnellement.",
        'logoUrl' => $pick(0),
        'bannerUrl' => $pick(1),
        'tags' => ['Google Tech', 'Web', 'Mobile', 'Cloud', 'AI / ML'],
        'whatsappUrl' => 'https://chat.whatsapp.com/GdgLomeCommunityExample',
        'telegramUrl' => 'https://t.me/gdglome',
        'linkedinUrl' => 'https://linkedin.com/company/gdg-lome',
        'twitterUrl' => 'https://twitter.com/gdglome',
        'websiteUrl' => 'https://gdg.community.dev/gdg-lome/',
        'country' => 'Togo',
        'city' => 'Lomé',
        'lat' => 6.1650, 'lng' => 1.2210,
        'leaderName' => 'Koffi Mensah',
        'leaderEmail' => 'koffi.mensah@example.com',
        'leaderPhone' => '+228 90 12 34 56',
        'leaderPhotoUrl' => $pick(2),
        'leaderBio' => 'Organisateur GDG Lomé depuis 2018, développeur Android passionné et mentor pour les juniors.',
        'coLeads' => [
            ['name' => 'Abla Tchalla', 'role' => 'Co-lead Cloud', 'photoUrl' => $pick(3), 'bio' => 'Spécialiste Google Cloud et formatrice.', 'linkedinUrl' => 'https://linkedin.com'],
            ['name' => 'Komla Agbeko', 'role' => 'Co-lead Mobile', 'photoUrl' => $pick(4), 'bio' => 'Développeur Flutter et animateur des meetups mobile.'],
        ],
        'gallery' => [
            $pick(5),
            $pick(6),
            $pick(7),
        ],
        'foundedYear' => 2017,
        'memberCount' => 850,
        'meetingInfo' => 'Meetup mensuel le 2e samedi à la Tech Hub Tokoin. Ateliers pratiques et sessions de code en groupe.',
        'publicEmail' => 'contact@gdglome.tg',
    ],
    [
        'name' => 'Women Techmakers Lomé',
        'shortDescription' => 'Autonomiser les femmes dans la tech au Togo — visibilité, mentorat et formation.',
        'description' => "Une communauté dédiée à la promotion et à l'autonomisation des femmes dans le secteur technologique au Togo. Nous offrons de la visibilité, de la formation professionnelle, du mentorat et créons un espace sécurisé pour inspirer plus de filles à embrasser les carrières STEM.",
        'mission' => "Créer un écosystème inclusif où les femmes togolaises brillent dans la tech, avec des rôles modèles visibles et un accompagnement concret vers l'emploi et l'entrepreneuriat.",
        'logoUrl' => $pick(8),
        'bannerUrl' => $pick(9),
        'tags' => ['Inclusion', 'Web', 'Mentorat', 'UX / UI'],
        'whatsappUrl' => 'https://chat.whatsapp.com/WtmLomeExample',
        'linkedinUrl' => 'https://linkedin.com/company/wtm-lome',
        'twitterUrl' => 'https://twitter.com/wtmlome',
        'country' => 'Togo',
        'city' => 'Lomé',
        'lat' => 6.1670, 'lng' => 1.2220,
        'leaderName' => 'Afiwa Sika',
        'leaderEmail' => 'afiwa.sika@example.com',
        'leaderPhone' => '+228 91 23 45 67',
        'leaderPhotoUrl' => $pick(10),
        'leaderBio' => 'Ambassadrice Women Techmakers, ingénieure logiciel et militante pour l\'inclusion numérique au Togo.',
        'coLeads' => [
            ['name' => 'Edem Kossi', 'role' => 'Co-lead Mentorat', 'photoUrl' => $pick(0), 'bio' => 'Coach carrière et responsable du programme de mentorat WTM.'],
            ['name' => 'Mawuli Dossou', 'role' => 'Co-lead Communication', 'photoUrl' => $pick(1), 'bio' => 'Community manager et créatrice de contenu tech.'],
        ],
        'gallery' => [
            $pick(2),
            $pick(3),
        ],
        'foundedYear' => 2019,
        'memberCount' => 420,
        'meetingInfo' => 'Sessions bi-mensuelles : ateliers UX, tables rondes carrière et hackathons inclusifs.',
        'publicEmail' => 'hello@wtmlome.tg',
    ],
    [
        'name' => 'Togo Cybersecurity Community',
        'description' => "Regroupement de professionnels et d'étudiants passionnés de sécurité de l'information au Togo. Ateliers pratiques sur le Pentesting, la défense des réseaux, l'analyse de malwares et la sensibilisation au hacking éthique.",
        'shortDescription' => 'La communauté cybersécurité de référence au Togo.',
        'mission' => 'Défendre un cyberespace togolais plus sûr par la formation et la sensibilisation.',
        'logoUrl' => $pick(4),
        'bannerUrl' => $pick(5),
        'tags' => ['Sécurité', 'Ethical Hacking', 'Réseaux'],
        'whatsappUrl' => 'https://chat.whatsapp.com/TogoCybersec',
        'telegramUrl' => 'https://t.me/togocybersec',
        'linkedinUrl' => 'https://linkedin.com/company/togo-cybersecurity',
        'websiteUrl' => 'https://cybersec.tg',
        'country' => 'Togo',
        'city' => 'Lomé',
        'lat' => 6.1810, 'lng' => 1.1620,
        'leaderName' => 'Folly Koffi',
        'leaderEmail' => 'folly.cyber@example.com',
        'leaderPhone' => '+228 92 34 56 78',
        'leaderPhotoUrl' => $pick(6),
        'foundedYear' => 2020,
        'memberCount' => 280,
        'meetingInfo' => 'CTF mensuel et ateliers pentest le dernier vendredi du mois.',
    ],
    [
        'name' => 'Lomé Data Science',
        'description' => "La communauté de référence pour le Machine Learning, le Deep Learning et le Big Data au Togo.",
        'shortDescription' => 'Bootcamps Python, R et compétitions de data au Togo.',
        'logoUrl' => $pick(7),
        'bannerUrl' => $pick(8),
        'tags' => ['Data Science', 'Python', 'AI / ML'],
        'telegramUrl' => 'https://t.me/lomedatascience',
        'linkedinUrl' => 'https://linkedin.com/company/lome-data-science',
        'twitterUrl' => 'https://twitter.com/lomedata',
        'country' => 'Togo',
        'city' => 'Lomé',
        'lat' => 6.1950, 'lng' => 1.1980,
        'leaderName' => 'Kokou Mawulikplim',
        'leaderEmail' => 'kokou.data@example.com',
        'leaderPhone' => '+228 93 45 67 89',
        'foundedYear' => 2021,
        'memberCount' => 190,
    ],
    [
        'name' => 'Designers du Togo (UX/UI)',
        'description' => "Une communauté vibrante réunissant les UX/UI designers, graphistes, et concepteurs de produits numériques togolais.",
        'shortDescription' => 'Design centré utilisateur et ateliers Figma pour les créatifs togolais.',
        'logoUrl' => $pick(9),
        'bannerUrl' => $pick(10),
        'tags' => ['UX / UI', 'Design', 'Figma'],
        'whatsappUrl' => 'https://chat.whatsapp.com/TogoDesigners',
        'twitterUrl' => 'https://twitter.com/designerstg',
        'websiteUrl' => 'https://designers.tg',
        'country' => 'Togo',
        'city' => 'Lomé',
        'lat' => 6.1360, 'lng' => 1.2020,
        'leaderName' => 'Yawo Mawunyo',
        'leaderEmail' => 'yawo.design@example.com',
        'leaderPhone' => '+228 97 65 43 21',
        'foundedYear' => 2018,
        'memberCount' => 310,
    ],
    [
        'name' => 'Lomé Dev Club',
        'description' => "Un club d'échange de compétences sur les technos modernes (React, Next.js, Flutter, Node.js, Rust).",
        'shortDescription' => 'Revues de code hebdomadaires et entraide pour les devs togolais.',
        'logoUrl' => $pick(0),
        'bannerUrl' => $pick(1),
        'tags' => ['React', 'NodeJS', 'Flutter', 'Open Source'],
        'whatsappUrl' => 'https://chat.whatsapp.com/LomeDevClub',
        'telegramUrl' => 'https://t.me/lomedevclub',
        'linkedinUrl' => 'https://linkedin.com/company/lomedevclub',
        'country' => 'Togo',
        'city' => 'Lomé',
        'lat' => 6.2250, 'lng' => 1.2140,
        'leaderName' => 'Komi Agbessi',
        'leaderEmail' => 'komi.dev@example.com',
        'leaderPhone' => '+228 98 76 54 32',
        'foundedYear' => 2019,
        'memberCount' => 520,
        'meetingInfo' => 'Sessions hebdomadaires le jeudi soir — revue de code et pair programming.',
    ],
];
